# Generated by Django 5.0 on 2023-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=255)),
                ('playlist_length', models.IntegerField()),
            ],
        ),
    ]
