# Generated by Django 5.0 on 2023-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_helper', '0003_alter_playlist_playlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('video_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_length',
            field=models.CharField(max_length=100),
        ),
    ]
